homeApp/urls.py
from django.urls import path
from . import views

app_name = 'homeApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('Gallery/', views.gallery, name='gallery'),
    path('Schedule/',views.schedule, name='activities'),
    path('Schedule/delete', views.delete),
    # dilanjutkan ...
]

storyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
]

homeApp/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=25)
    kategori = models.CharField(null=True, max_length=25)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

homeApp/forms.py
from . import models
from django import forms
import datetime

class ListActivities(forms.ModelForm):
        nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Nama Kegiatan",
                }))
        tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Tempat",
                }))
        kategori = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Kategori",
                }))
        tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }), initial=datetime.datetime.now() )
        waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }), initial=datetime.datetime.now() ) 


        class Meta:
                model = models.Jadwal
                fields = ["nama_kegiatan", "kategori", "tempat", "tanggal", "waktu"]

homeApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from .forms import ListActivities
from .models import Jadwal

import datetime


# Create your views here.

def home(request):
	return render(request, 'Home.html')

def gallery(request):
	return render(request, 'Gallery.html')

def schedule(request):
	if request.method == "POST":
		fillForm = ListActivities(request.POST)
		if fillForm.is_valid():
			fillForm.save()
			return redirect('homeApp:activities')
	else:
		fillForm = ListActivities()

	task = Jadwal.objects.order_by("tanggal", "waktu")
	time = datetime.datetime.now()
	tasks = {
		'form' : fillForm,
		'tasksname' : task,
		'time' : datetime.datetime.now()
	}
	return render(request, 'Schedule.html', tasks )

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Jadwal.objects.get(id=id).delete()
    return redirect('homeApp:activities')

homeApp/templates/Gallery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Karin Patricia's Profile">
    <meta name="author" content="A.K.">

    <title>Karin's Gallery</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/bootstrap.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Custom CSS -->  
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Reem+Kufi">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Abhaya+Libre">


</head>

<body id="myPage"  data-spy="scroll" data-target=".navbar" data-offset="60">

    <!-- ----- Header & Navigation ----- -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #303030;">
        <a class="navbar-brand" href="{% url 'homeApp:home' %}">
            <img src="{% static 'Logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#events">events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#personal">personal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#shot">shots</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- ----- Events Section ----- -->
    <div class="bg-events bg-section" id="events">
        <div class="container-fluid">
            <h1 class="container-h1"> e v e n t s</h1>
            <div class="row image">
                <img src="{% static 'act01.jpg' %}" style="max-width: 250px">
                <img src="{% static 'act02.jpg' %}" style="max-width: 250px">
                <img src="{% static 'act03.jpg' %}" style="max-width: 250px">
            </div>
            <div class="row image" style="margin-bottom: 80px">
                <img src="{% static 'act04.jpg' %}" style="max-width: 250px">
                <img src="{% static 'act05.jpg' %}" style="max-width: 250px">
                <img src="{% static 'act06.jpg' %}" style="max-width: 250px">
            </div>
        </div>
    </div>

    <!-- ----- Personal Section ----- -->
    <div class="bg-personal bg-section" id="personal">
        <div class="container-fluid">
            <h1 class="container-h1"> p e r s o n a l </h1>
            <div class="row image">
                <img src="{% static 'self01.jpg' %}" style="max-width: 250px">
                <img src="{% static 'self02.jpg' %}" style="max-width: 250px">
                <img src="{% static 'self03.jpeg' %}" style="max-width: 250px">
                <img src="{% static 'self04.jpeg' %}" style="max-width: 250px">
            </div>
            <div class="row image" style="margin-bottom: 80px">
                <img src="{% static 'self05.jpg' %}" style="max-width: 250px">
                <img src="{% static 'self06.jpg' %}" style="max-width: 250px">
                <img src="{% static 'self07.jpeg' %}" style="max-width: 250px">
                <img src="{% static 'self08.jpeg' %}" style="max-width: 250px">
            </div>  
        </div>
    </div>

    <!-- ----- Shots Section ----- -->
    <div class="bg-shot bg-section" id="shot">
        <div class="container-fluid">
            <h1 class="container-h1"> s h o t s </h1>
            <div class="row image">
                <img src="{% static 'interest01.jpg' %}" class="rotateimg90" style="max-width: 250px">
                <img src="{% static 'interest02.jpg' %}" class="rotateimg90" style="max-width: 250px">
                <img src="{% static 'interest03.jpg' %}" class="rotateimg90" style="max-width: 250px">
                <img src="{% static 'interest04.jpg' %}" class="rotateimg90" style="max-width: 250px">
            </div>
            <div class="row image" style="margin-bottom: 50px">
                <img src="{% static 'interest05.jpg' %}" style="max-width: 250px">
                <img src="{% static 'interest06.jpg' %}" style="max-width: 250px">
                <img src="{% static 'interest07.jpg' %}" class="rotateimg90" style="max-width: 250px">
                <img src="{% static 'interest08.jpg' %}" style="max-width: 250px">
            </div> 
        </div>
    </div>

    <!-- ----- Contact ----- -->
    <div class="bg-contact bg-section" id="contact">
        <div class="container-fluid" style="text-align: center;">
            <h6> c o n t a c t </h6>
            <div class="image">
                <a href="https://www.instagram.com/karinptrc/?hl=en">
                    <img src="{% static 'instagram.png' %}">
                </a>
                <a href="https://www.pinterest.co.kr/karinptrc/">
                    <img src="{% static 'pinterest.png' %}" class="middle">
                </a>
                <a href="https://www.linkedin.com/in/karin-patricia-401093164/">
                    <img src="{% static 'linkedin.png' %}">
                </a>
            </div>
            <div>
                <p>karinptrc@gmail.com</p>
            </div> 
        </div>
    </div>
    
</body>
</html>

homeApp/templates/Home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Karin Patricia's Profile">
    <meta name="author" content="A.K.">

    <title>Karin's Profile</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <!-- Custom CSS -->  
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Reem+Kufi">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Abhaya+Libre">


</head>

<body id="myPage"  data-spy="scroll" data-target=".navbar" data-offset="60">

    <!-- ----- Header & Navigation ----- -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="#">
            <img src="{% static 'Logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homeApp:activities' %}">schedule</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homeApp:gallery' %}">gallery</a>
                </li>
            </ul>
        </div>  
    </nav>

    <div class="bgprofile">
        <div class="container-fluid">
        </div>
    </div>

    <!-- ----- Profile ----- -->
    <div class="bg-profile bg-section" id="profile">
        <div class="container-fluid">
            <div class="container-h1"></div>
            <h1 class="container-h1"> p r o f i l e </h1>
            <div class="row">
                <div class="col-sm-6">
                    <div class="row">
                        <div class="col-md-6 offset-md-2">
                            <img src="{% static 'Profile.jpg' %}" class="image" style="max-width: 250px">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6 offset-md-2">
                            <ul>
                                <li>
                                    <h6> UNIVERSITAS INDONESIA </h6>
                                    <p> Information System </p>
                                    <p> Faculty of Computer Science </p>
                                    <p> 2018 - present </p>
                                </li>
                                <br>
                                <li>
                                    <h6> SMA NEGERI 1 JAKARTA </h6>
                                    <p> Science </p>
                                    <p> 2015 - 2018 </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div> <span class="border-top" style="color: black; width: 10px;"></span>
                        <a href="https://drive.google.com/open?id=1Srp_xzx3VOWRmCAal0LuGcz-VwpT4T-E"> See my resume here.</a>
                    </div>
                </div>                

                <div class="col-sm-6">
                    <div class="picture">
                        <img src="{% static 'BGpicture.png' %}">
                        <div class="picture2">
                            <img src="{% static 'MPK.jpg' %}" alt="MPK" style="max-width: 250px">
                        </div>
                        <div class="picture3">
                            <img src="{% static 'Natal SRKP.jpg' %}" alt="Natal SRKP" style="max-width: 350px">
                        </div>
                        <div class="picture4">
                            <img src="{% static 'Skills.png' %}" style="max-width: 250px">
                        </div>
                        
                    </div> 
                </div>     
            </div>
    </div>

    <!-- ----- Interest ----- -->
     <div class="bg-interest bg-section" id="interest">
        <div class="container-fluid">
            <h1 class="container-h1"> i n t e r e s t </h1>
            <div class="image">
                <img src="{% static 'interest01.jpg' %}" class="rotateimg90" style="max-width: 250px">
                <img src="{% static 'interest02.jpg' %}" class="rotateimg90 middle" style="max-width: 250px">
                <img src="{% static 'interest03.jpg' %}" class="rotateimg90" style="max-width: 250px">
            </div>  
        </div>
    </div>




    <!-- ----- Contact ----- -->
    <div class="bg-contact bg-section" id="contact">
        <div class="container-fluid" style="text-align: center;">
            <h6> c o n t a c t </h6>
            <div class="image">
                <a href="https://www.instagram.com/karinptrc/?hl=en">
                    <img src="{% static 'instagram.png' %}">
                </a>
                <a href="https://www.pinterest.co.kr/karinptrc/">
                    <img src="{% static 'pinterest.png' %}" class="middle">
                </a>
                <a href="https://www.linkedin.com/in/karin-patricia-401093164/">
                    <img src="{% static 'linkedin.png' %}">
                </a>
            </div>
            <div>
                <p>karinptrc@gmail.com</p>
            </div> 
        </div>
    </div>

</body>
</html>

homeApp/templates/Schedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Karin Patricia's Schedule">
    <meta name="author" content="A.K.">

    <title>Karin's Schedule</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/bootstrap.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Custom CSS -->  
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Reem+Kufi">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Abhaya+Libre">


</head>

<body id="myPage"  data-spy="scroll" data-target=".navbar" data-offset="60">

    <!-- ----- Header & Navigation ----- -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #303030">
        <a class="navbar-brand" href="{% url 'homeApp:home' %}">
            <img src="{% static 'Logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </nav>

    <!-- ----- Add Schedule ---- -->
    <div class="bg-schedule">
        <div class="container-fluid">
            
        

        <div class="row">
        <div class="col-4"> 
            <h1>{{ time }}</h1>
            <h1 class="container-h1" style="margin-top: 100px">add your new task below</h1>
        <form method="POST" class="form">
            {% csrf_token %}
            <p>Nama Kegiatan</p>
            {{ form.nama_kegiatan }}
            <br>
            <p>Tempat</p>
            {{ form.tempat }}
            <br>
            <p>Kategori</p>
            {{ form.kategori }}
            <br>
            <p>Tanggal</p>
            {{ form.tanggal }}
            <br>
            <p> Waktu </p>
            {{ form.waktu }}
        
        <div>
            <input type="submit" value="Submit" />
        </div>
        
        </form>
        </div>

        

        <div class="col-8">
        <h1 class="container-h1" style="margin-top: 100px">list activities</h1>
        {% for task in tasksname %}
                <h2>[{{task.kategori}}] --- {{ task.nama_kegiatan }}</h2>
                <div class="flex">
                    <div>
                        <h4>di {{ task.tempat }} </h4>
                        <p>pada {{task.tanggal}} --- {{task.waktu}} </p>
                    </div>
                    <form action="delete" method="POST" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ task.id }}" name="id" />
                        <input type="submit" value="Delete" />
                    </form>
                </div>
        {% endfor %}
        </div>


        </div>
        </div>
        
    </div>
<!--
    <!- ----- Contact ----- --
    <div class="bg-contact bg-section" id="contact">
        <div class="container-fluid" style="text-align: center;">
            <h6> c o n t a c t </h6>
            <div class="image">
                <a href="https://www.instagram.com/karinptrc/?hl=en">
                    <img src="{% static 'instagram.png' %}">
                </a>
                <a href="https://www.pinterest.co.kr/karinptrc/">
                    <img src="{% static 'pinterest.png' %}" class="middle">
                </a>
                <a href="https://www.linkedin.com/in/karin-patricia-401093164/">
                    <img src="{% static 'linkedin.png' %}">
                </a>
            </div>
            <div>
                <p>karinptrc@gmail.com</p>
            </div> 
        </div>
    </div>
-->
    
</body>
</html>